CREATE DATABASE juego;

CREATE TABLE JUGADOR
(
id INT NOT NULL,
nombre VARCHAR (30) NOT NULL,
puntaje INT NOT NULL,
fecha DATE NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE PREGUNTA
(
idPreg INT NOT NULL,
nivel INT NOT NULL,
descripcion VARCHAR (255) NOT NULL,
PRIMARY KEY (idPreg) 
);

CREATE TABLE RESPUESTA
(
idRespuesta INT NOT NULL,
descripcion VARCHAR (255) NOT NULL,
idPreg INT NOT NULL, 
respCorrecta BIT NOT NULL,
PRIMARY KEY (idRespuesta),
CONSTRAINT FK_idPreg FOREIGN KEY (idPreg) REFERENCES PREGUNTA(idPreg)
);

INSERT INTO PREGUNTA (idPreg, nivel, descripcion)
VALUES 
(1, 1, '¿Que representa en un diagrama de flujo el rombo?'),
(2, 1, '¿Que es un algoritmo?'),
(3, 1, '¿Ejemplo de software libre?'),
(4, 1, '¿Ejemplo de tipo de dato Entero?'),
(5, 1, '¿Ejemplo de tipo de dato cadena?'),
(6, 2, 'Son los tipos de datos que se manejan en Programación.'),
(7, 2, 'Son los tipos de variables que se manejan en Programación.'),
(8, 2, 'Un bucle o ciclo es:'),
(9, 2, '¿Que es un diagrama de flujo?'),
(10, 2, '¿Que es una variable en programación?'),
(11, 3, '¿Qué es  JavaScript?'),
(12, 3, '¿Que es una Clase en Programación?'),
(13, 3, '¿Que es un atributo en Programación ?'),
(14, 3, '¿Que es un objeto en Programación orientado a objetos?'),
(15, 3, '¿Que es un Constructor en Java?'),
(16, 4, '¿Que es un Lenguaje de alto nivel?'),
(17, 4, '¿Que es una variable local en Programación orientado a objetos?'),
(18, 4, '¿Que significa JDK?'),
(19, 4, '¿Que es un Lenguaje Maquina?'),
(20, 4, '¿Para la solución del problema de calcular el promedio de tres notas de un alumno, Cuál sería el proceso?'),
(21, 5, '¿Qué es la programación estructurada?'),
(22, 5, 'Son nombres de lenguajes de programación orientado a objetos.'),
(23, 5, '¿Que es un Lenguaje Ensamblador?'),
(24, 5, '¿Cuál es la diferencia entre un bit y un Byte?'),
(25, 5, '¿Qué es el compilador Java?');


INSERT INTO RESPUESTA(idRespuesta, descripcion, idPreg, respCorrecta)
VALUES 
(1, 'Un proceso', 1, 0),
(2, 'Un almacén', 1, 0),
(3, 'Una decisión', 1, 1),
(4, 'Ninguna de las anteriores', 1, 0),
(5, 'Combinación de pasos aleatorios dispuestos de forma organizada para resolver un problema', 2, 0),
(6, 'Combinación de pasos lógicos dispuestos de forma organizada para resolver un problema', 2, 1),
(7, 'Combinación de pasos lógicos dispuestos de forma desordenada para resolver un problema', 2, 0),
(8, 'Combinación de pasos aleatorios dispuestos de forma desordenada para resolver un problema', 2, 0),
(9, 'Windows', 3, 0),
(10, 'Linux', 3, 1),
(11, 'MacOS', 3, 0),
(12, 'Internet explorer', 3, 0),
(13, '10', 4, 1),
(14, '10.6', 4, 0),
(15, 'Entero', 4, 0),
(16, 'C', 4, 0),
(17, '50', 5, 0),
(18, 'Entero', 5, 1),
(19, 'A', 5, 0),
(20, '11.636', 5, 0),
(21, 'Tipo Java, C++, Python, Visual .net, Visual Basic, entre otros.', 6, 0),
(22, 'Cadena, Boleano, Carácter, Numeros, alfanuemrico, Entero.', 6, 1),
(23, 'String, Boolean, Char, Integer, int, etc.', 6, 0),
(24, 'Simbólicos, de estructura, de cadena, de complemento, generales, particulares, entre otros.', 6, 0),
(25, 'Tipo Java, C++, Python, Visual .net, Visual Basic, entre otros.', 7, 0),
(26, 'Cadena, Boleano, Carácter, Numeros, alfanuemrico, Entero.', 7, 0),
(27, 'String, Boolean, Char, Integer, int, etc.', 7, 1),
(28, 'Simbólicos, de estructura, de cadena, de complemento, generales, particulares, entre otros.', 7, 0),
(29, 'Una sentencia que permite decidir si se ejecuta o no se ejecuta una sola vez un bloque aislado de código.', 8, 0),
(30, 'Una sentencia que permite ejecutar un bloque aislado de código varias veces hasta que se cumpla (o deje de cumplirse) la condición asignada al bucle.', 8, 1),
(31, 'Una sentencia que ejecuta otra sentencia que a su vez ejecuta la primera sentencia.', 8, 0),
(32, 'Una sentencia que permite ejecutar un bloque aislado de código varias veces hasta que no se cumpla (o no deje de cumplirse) la condición asignada al bucle.', 8, 0),
(33, 'Es la representación de un pseudocodigo.', 9, 0),
(34, 'Es la representación de un problema.', 9, 0),
(35, 'Es la representación gráfica de un algoritmo.', 9, 1),
(36, 'Es la representación gráfica de un ritmoalgo.', 9, 0),
(37, 'Espacio de memoria reservado para almacenar un dato.', 10, 1),
(38, 'Espacio de memoria reservado para almacenar imagenes.', 10, 0),
(39, 'Espacio de memoria reservado para almacenar un numero.', 10, 0),
(40, 'Espacio de memoria reservado para almacenar letras.', 10, 0),
(41, 'Un programa', 11, 0),
(42, 'Algoritmo', 11, 0),
(43, 'Lenguaje de programación', 11, 1),
(44, 'Pseudocódigo', 11, 0),
(45, 'Es un programa contable que traduce un programa escrito en un lenguaje de programación a otro lenguaje de programación.', 12, 0),
(46, 'Es un programa que transforma código fuente escrito en java a un código neutral a la plataforma conocido como java.', 12, 0),
(47, 'Es un atributo de una parte de los datos que indica al ordenador (y/o al programador) algo sobre la clase de datos sobre los que se va a procesar.', 12, 0),
(48, 'Es una colección o conjunto de objetos que comparten características comunes entre si.', 12, 1),
(49, 'Son las cosas individuales que diferencian una clase de objetos de otros y determinan la apariencia, estado y otras cualidades de la clase.', 13, 1),
(50, 'Es un programa que transforma código fuente escrito en java a un código neutral a la plataforma conocido como java.', 13, 0),
(51, 'Es un entorno de desarrollo integrado libre, hecho principalmente para el lenguaje de programación Java.', 13, 0),
(52, 'Es un atributo de una parte de los datos que indica al ordenador (y/o al programador) algo sobre la clase de datos sobre los que se va a procesar.', 13, 0),
(53, 'Elemento independiente de un programa de computadora que representa a un grupo asociado de características diseñado para tareas especificas.', 14, 1),
(54, 'Es un programa que transforma código fuente escrito en java a un código neutral a la plataforma conocido como java.', 14, 0),
(55, 'Es aquel elemento que tiene relación con el almacenamiento de la Información y sus usos; es más cercana a las Personas y Computadoras', 14, 0),
(56, 'Es un atributo de una parte de los datos que indica al ordenador (y/o al programador) algo sobre la clase de datos sobre los que se va a procesar.', 14, 0),
(57, 'Es un compilador estable y potente para la solución de problemas humanos y los entienda físicamente la PC.', 15, 0),
(58, 'Es un método especial de una clase que se llama automáticamente siempre que se declara un objeto de esa clase.', 15, 1),
(59, 'Es un entorno de desarrollo integrado libre, hecho principalmente para el lenguaje de programación Java.', 15, 0),
(60, 'Es módulo ordenado de elementos para la computadora que se encuentran interrelacionados y que interactúan entre sí, en apoyo al usuario.', 15, 0),
(61, 'Es un compilador estable y potente para la solución de problemas humanos y los entienda físicamente la PC.', 16, 0),
(62, 'Es el sistema de códigos directamente interpretable (0 y 1) por un circuito microprogramable, como el microprocesador de una computadora.', 16, 0),
(63, 'Es un es un lenguaje de programación para los computadores, microprocesadores, microcontroladores y otros circuitos integrados programables.', 16, 0),
(64, 'Se caracteriza por expresar los algoritmos de una manera adecuada a la capacidad cognitiva humana, en lugar de la capacidad ejecutora de las máquinas', 16, 1),
(65, 'Estas se utilizan dentro de las funciones miembro o métodos.', 17, 1),
(66, 'Es un nombre que se asocia con una porción de la memoria del ordenador, en la que se guarda el valor asignado a dicha variable.', 17, 0),
(67, 'Es un grupo de sentencias que se comportan como una unidad.', 17, 0),
(68, 'Es una orden que se le da al programa para realizar una tarea específica.', 17, 0),
(69, 'Java Development Kit', 18, 1),
(70, 'Java Distance kilobye', 18, 0),
(71, 'Distrit Java Kit', 18, 0),
(72, 'Kilobyte Java Development', 18, 0),
(73, 'Es un lenguaje de programación de bajo nivel para los computadores, microprocesadores, microcontroladores y otros circuitos integrados programables.', 19, 0),
(74, 'Es el sistema de códigos directamente interpretable (0 y 1) por un circuito microprogramable, como el microprocesador de una computadora.', 19, 0),
(75, 'Se caracteriza por expresar los algoritmos de una manera adecuada a la capacidad cognitiva humana, en lugar de la capacidad ejecutora de las máquinas.', 19, 1),
(76, 'Es un lenguaje o Sfw diseñado para describir un conjunto de acciones consecutivas que un equipo debe ejecutar.', 19, 0),
(77, 'Promedio=(Nota1+Nota2+Nota3)/3', 20, 1),
(78, 'Promedio=(Nota1+Nota2)+Nota3/3', 20, 0),
(79, 'Promedio=Nota1+(Nota2+Nota3)/3', 20, 0),
(80, 'Promedio=Nota1+Nota2+Nota3/3', 20, 0),
(81, 'Es un paradigma de programación orientado a mejorar la estructuras de los datos.', 21, 0),
(82, 'Es una secuencia de información que cuida los datos para ser procesados.', 21, 0),
(83, 'Es un paradigma de programación orientado a mejorar la claridad, calidad y tiempo de desarrollo de un programa', 21, 1),
(84, 'Ninguna de las anteriores', 21, 0),
(85, 'Java, C++, Smalltalk, Python, Object Pascal, Visual .net, Visual Basic, Delphi, Perl, entre otros.', 22, 1),
(86, 'Visual Basic, Visual C++, Visual DialogScript, Visual Foxpro, Ensamblador, Borland c, Turbo C. entre otros', 22, 0),
(87, 'HTML, XML, VML, Java, PHP, C++, Fortran, Cobol, Lisp, entre otros', 22, 0),
(88, 'Actionscript, COBOL, C++, .NET, PHP, Simula, PowerBuilder, Maya, entre otros.', 22, 0),
(89, 'Es un lenguaje de programación de bajo nivel para los computadores, microprocesadores, microcontroladores y otros circuitos integrados programables.', 23, 1),
(90, 'Es el sistema de códigos directamente interpretable (0 y 1) por un circuito microprogramable, como el microprocesador de una computadora.', 23, 0),
(91, 'Se caracteriza por expresar los algoritmos de una manera adecuada a la capacidad cognitiva humana, en lugar de la capacidad ejecutora de las máquinas.', 23, 0),
(92, 'Es un lenguaje o Sfw diseñado para describir un conjunto de acciones consecutivas que un equipo debe ejecutar.', 23, 0),
(93, 'En que uno corresponde a la unidad maxima de Memoria y el otro es un conjunto de 6 a 8 bytes', 24, 0),
(94, 'La diferencia es que uno es de datos y otro es conjunto de datos.', 24, 0),
(95, 'La diferencia es de 1024 Mb de almacenamiento.', 24, 0),
(96, 'En que uno corresponde a la unidad mínima de Memoria y el otro es un conjunto de 6 a 8 bits', 24, 1),
(97, 'Es un programa contable que traduce un programa escrito en un lenguaje de programación a otro lenguaje de programación.', 25, 0),
(98, 'Es un programa que transforma código fuente escrito en java a un código neutral a la plataforma conocido como java.', 25, 1),
(99, 'Es un entorno de desarrollo integrado libre, hecho principalmente para el lenguaje de programación Java.', 25, 0),
(100, 'Es un atributo de una parte de los datos que indica al ordenador (y/o al programador) algo sobre la clase de datos sobre los que se va a procesar.', 25, 0);


